### ISSUE TITLE
Review support of warehouse types

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1047]
So far, we had decided to support, in the warehouse drivers, only the types for which the set of values matched exactly with that of the corresponding type in Meergo.

~~We have now decided to relax this requirement (after a discussion with @gazerro, 2024-09-26), making it necessary for the warehouse type to be a superset, not necessarily the same set. This allows for wider types support.~~

After a discussion on September 30, 2024, with @gazerro, we decided that the criterion identified in the other discussion is too permissive, so there is actually no formal criterion, and the choice of types to support must be discussed on a case-by-case basis.

### TODO

* [x] Update the documentation in the README file of the Datastore (done in https://github.com/open2b/meergo/commit/c923d9fbf369bd576a20cf899b6dc4394976e2ea)
* [x] Support the `Inet` type in PostgreSQL (this comes from [a closed issue](https://github.com/open2b/meergo-rewritten/issues/1041)) (see https://github.com/open2b/meergo/pull/1050)
* [x] Update the README of the Datastore with the new criterion determined on September 30, 2024 (done in https://github.com/open2b/meergo/commit/6149e0328da6dc2545e156e41cf9b001d6dfb747)
* [x] Review support for various types, in PostgreSQL (adding any TODOs here if necessary)
* [x] Review support for various types, in Snowflake (adding any TODOs here if necessary). Discussed in the issue https://github.com/open2b/meergo-rewritten/issues/1054.
* [x] Investigate on the support of `Date` and `DateTime`. Are there problems that still applies? See [this closed issue](https://github.com/open2b/meergo-rewritten/issues/584) for further details.
* [x] Update the UI, if and where necessary

**Comment by zapateo** [comment]
I am closing this issue, as it is a meta-issue in which the various points have been resolved, except for the types in Snowflake that are discussed in issue https://github.com/open2b/meergo-rewritten/issues/1054.
