### ISSUE TITLE
Add a richer default workspace schema

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1075]
Since the workspace is created with a connected and known warehouse, initialize a schema that is already rich, depending on the type of connected warehouse. Remember to edit the file `doc/src/changing-user-schema.md`.

EDIT: Since all warehouses will support all types, it doesn't really matter if you know the data warehouse beforehand; anyway, the issue still needs to be implemented.

Additionally, since we put a default schema, we can also directly configure default displayed properties.

## TODO

* [x] Make the user schema an API parameter instead of being hard-coded (https://github.com/open2b/meergo/pull/1169)
* [x] Simplify the tests. See the TODO in the meergotester file regarding the schema to use in the tests (done in bb6a33db00f9509b01a450cfafa66bc8465235e4)
* [x] ~~In meergo-cli, add an option to create a default schema, perhaps the same schema that is created by default by the UI~~ meergo-cli does not exist anymore
* [x] Enrich the user schema with good default properties (https://github.com/open2b/meergo/pull/1174)
* [x] Set the displayed properties from the UI on the created workspace (discussed in https://github.com/open2b/meergo-rewritten/issues/1186)
* [x] Decide a "definitive" user schema (discussed in https://github.com/open2b/meergo-rewritten/issues/1187)

**Comment by zapateo** [comment]
All the points above have been marked as completed or discussed in separated issues, so this issue can now be closed.
