### ISSUE TITLE
test: clean and simplify test infrastructure since we use testcontainers

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1154]
We should clean and simplify test infrastructure since we use _testcontainers_.

## TODO

* [x] Remove the configuration file, since we are using testcontainers (done in https://github.com/open2b/meergo/commit/95d481578dd92673ecff0847beb3e83073bc8756)
* [x] Check the references in the code to this issue, `https://github.com/open2b/meergo-rewritten/issues/1154` (done in https://github.com/open2b/meergo/commit/95d481578dd92673ecff0847beb3e83073bc8756)
* [x] Make the host configurable through and environment variable (done in https://github.com/open2b/meergo/commit/81b4dbb345514f46dc15232567eee089b94e6667)
* [x] Document the environment variables used by the tests (done in https://github.com/open2b/meergo/commit/81b4dbb345514f46dc15232567eee089b94e6667)
* [x] Consider whether to "virtualize", or make available in another way, the Python executable used by the tests. (done in c83b21a5fcc96bec4cc1d449e43fa519ebf8e682)
* [x] Clean up the test infrastructure by checking if there is anything that can be removed/simplified

**Comment by zapateo** [comment]
All the points above have been completed, so I'm closing this issue.
