### ISSUE TITLE
core: accept property paths instead of just property names inside InProperties and OutProperties of transformation functions

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1197]
## Description

Accept property paths instead of just property names inside InProperties and OutProperties of transformation functions.

## Motivation

This is because, when I write the code of a transformation function, I want to be able to select only specific properties, otherwise, if the connector exposes many properties (perhaps unrelated) inside a single Object, this forces me to select the entire Object, causing the action to skip if one of its sub-properties is modified.

## TODO

* [ ] Validation of the action
* [ ] Documentation of the action
* [ ] Code that actually uses those properties for executing the transformation function
* [ ] Aggiornare la documentazione sul branch con la doc. delle API
