### ISSUE TITLE
Change the names of Identity/Displayed/UpdateAt properties

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#672]
## Desired UI

* [x] The section in the UI should be called "Special properties" (done in [ui: use the term "Special properties" for every type of action](https://github.com/open2b/chichi/commit/7dbbd3fc01959d60b5712e6015c92e8dfe6386bd))
* [x] The labels should be "Identity", "Displayed", and "Last change time" (done in [ui: rename field labels for "special columns"](https://github.com/open2b/chichi/commit/f6228b152637e93c1ed397faad641e49f00e5c4c))
* [x] Identity Documentation: A property that uniquely identifies a user. (see https://github.com/open2b/chichi/issues/676)
* [x] Displayed Documentation: An additional property displayed to distinguish a user. (see https://github.com/open2b/chichi/issues/676)
* [x] Last change time Documentation: A property with the time of the last modification of a user. (see https://github.com/open2b/chichi/issues/676)

## Internal Field Names

* [x] IdentityProperty (done in [all: rename "unique ID column" to "identity property"](https://github.com/open2b/chichi/commit/a6fc88f3c7aab7f85c8b1121506c0789c6d05527))
* [x] DisplayedProperty (done in https://github.com/open2b/chichi/pull/677)
* [x] UpdatedAtColumn → LastChangeTimeProperty (done in [all: rename "updated at" to "last change time"](https://github.com/open2b/chichi/commit/94c6bf133a6e3e145df451695276310829770d07))
* [x] UpdatedAtFormat → LastChangeTimeFormat (done in [all: rename "updated at" to "last change time"](https://github.com/open2b/chichi/commit/94c6bf133a6e3e145df451695276310829770d07))

**Comment by zapateo** [comment]
All the points listed above have been completed, so this issue can be closed.
