### ISSUE TITLE
Simplify namings of identity resolution procedures (Connection Identity Resolution, Workspace Identity Resolution, ...)

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#790]
Following the various changes and simplifications, we should:

* stop using the term "Connection Identity Resolution" and just use "writing of identities"
* stop using the term "Workspace Identity Resolution" and just use "Identity Resolution"

## TODO

* [x] Update the documentation under "doc" (https://github.com/open2b/chichi/pull/789)
* [x] Rename `RunWorkspaceIdentityResolution` to `RunIdentityResolution`
* [x] Change all the comments in the code that refer to "Workspace Identity Resolution"
* [x] Update the graph we have in the doc

**Comment by zapateo** [comment]
All the points above have been marked as completed, so this issue can be closed.
