### ISSUE TITLE
apis: add comprenhensive tests on action validation

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#849]
### Tasks

* [x] Make `validateActionToSet` testable
* [x] Add some initial tests (done in 573ed6a6d60d86bd12cc310450583de23d430c9c)
* [x] Uncomment every commented test about actions
* [x] Decide what to do with the tests on the action creation that we already have under `/test`
* [ ] Reach a test coverage of 100% of the function that validates action
* [ ] (ideally) Test every valid action that can be created
* [ ] (ideally) Test every error returnable by invalid actions

**Comment by zapateo** [comment]
This issue made sense initially, when action tests were still absent (or extremely limited) and inconsistent behaviors from the APIs were frequent.

Now:

1. We have action validation tests that cover a high percentage (although not yet 100%) of the code
2. Action validation problems are rarely encountered

For this reason, adding action validation tests has, in my opinion, no precedence over adding tests on other parts of the software. For this reason, I am closing the issue.
