### ISSUE TITLE
apis: formalize and complete validation of actions

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#855]
## TODO

* [x] Review the validation of the "Enable" field (it looks like it is correct)
* [x] Add tests on the validation (we have a dedicated issue on that, open2b/meergo-rewritten#849, so it's not discussed here)
* [x] Review the documentation of actions fields, both in the code and in additional documentation (Markdown files, docs, etc...)
* [x] Review the validation done by the APIs and ensure it is correct and complete

**Comment by zapateo** [comment]
The above points seem to be resolved. If there is anything left, it is something we do not see now and will come out with deep testing / code review. For action validation tests we already have another issue, https://github.com/open2b/chichi/issues/849. This issue does not add anything, so I am closing it.
