### ISSUE TITLE
Changes to the Identity Resolution for the first release

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#960]
Here is a list of changes to be made to the Identity Resolution that are necessary for the first release of the software.

### TODOs

* [x] Remove the automatic execution of the IR on events, making necessary to start it manually. Done in https://github.com/open2b/meergo/commit/ad47928e197eba40e0c7cc65f7de230aec6f5290.
* [x] Rename the UI screen called "Identifiers" (within the settings) to "Identity Resolution". See https://github.com/open2b/meergo/pull/962.
* [x] Move the Save button of the IR settings to the right, as we do in the page for setting the Workspace settings. Also reduce the page width. Done in https://github.com/open2b/meergo/commit/346784dda18025be2b3fa6be8c9bccac4be9ce8b.
* [x] Rename method "SetIdentifiers" to "SetIdentityResolutionSettings"
* [x] In the IR settings screen, add a checkbox to automatically start the IR when importing in batch; otherwise the IR can be executed only manually. The internal field could be named "RunIdentityResolutionOnBatchImport". See https://github.com/open2b/meergo/pull/964/.
* [x] Add a confirmation on the "Run identity resolution" button indicating that the operation may require some time. Done in https://github.com/open2b/meergo/commit/7c6948aa028aa35f0bffaf5b1e464cc0b7c1414d.

## Log Executions And Avoid Multiple Executions

This section has been moved to a separate issue: https://github.com/open2b/meergo-rewritten/issues/967

**Comment by zapateo** [comment]
Since all the points above have been resolved, this issue can be closed.
